# aroya_air/data.py
# Full dataset stored in `data` (as requested) and a compact `data_two_rows` for quick testing.

data = {
  "flights": [
    {
      "flight_id": "4A8577CC",
      "airline": "Singapore Airlines",
      "flight_number": "SQ617",
      "departure_city": "Hong Kong",
      "arrival_city": "Mumbai",
      "departure_airport": "Hong Kong International Airport",
      "arrival_airport": "Chhatrapati Shivaji Maharaj International Airport",
      "departure_airport_code": "HKG",
      "arrival_airport_code": "BOM",
      "departure_time": "2025-11-07T22:30:00+08:00",
      "arrival_time": "2025-11-08T00:30:00+05:30",
      "duration": "4h 30m",
      "aircraft_type": "Airbus A380-800",
      "baggage_allowance": "30kg + 7kg",
      "available_classes": ["Economy"],
      "price_usd": 1115.69,
      "seats_available": 3,
      "wifi_available": True,
      "inflight_entertainment": True,
      "status": "Cancelled"
    },
    {
      "flight_id": "A00804DA",
      "airline": "United Airlines",
      "flight_number": "UA664",
      "departure_city": "London",
      "arrival_city": "Jeddah",
      "departure_airport": "Heathrow Airport",
      "arrival_airport": "King Abdulaziz International Airport",
      "departure_airport_code": "LHR",
      "arrival_airport_code": "JED",
      "departure_time": "2025-11-05T20:30:00+00:00",
      "arrival_time": "2025-11-06T03:15:00+03:00",
      "duration": "3h 45m",
      "aircraft_type": "Airbus A320neo",
      "baggage_allowance": "15kg + 7kg",
      "available_classes": ["Economy"],
      "price_usd": 1576.01,
      "seats_available": 35,
      "wifi_available": True,
      "inflight_entertainment": True,
      "status": "Cancelled"
    },
    {
      "flight_id": "B811C18F",
      "airline": "Singapore Airlines",
      "flight_number": "SQ415",
      "departure_city": "Cairo",
      "arrival_city": "Amsterdam",
      "departure_airport": "Cairo International Airport",
      "arrival_airport": "Amsterdam Airport Schiphol",
      "departure_airport_code": "CAI",
      "arrival_airport_code": "AMS",
      "departure_time": "2025-11-18T04:45:00+02:00",
      "arrival_time": "2025-11-18T06:45:00+01:00",
      "duration": "3h 0m",
      "aircraft_type": "Airbus A350-900",
      "baggage_allowance": "20kg + 7kg",
      "available_classes": ["Economy", "Business"],
      "price_usd": 853.06,
      "seats_available": 2,
      "wifi_available": True,
      "inflight_entertainment": False,
      "status": "Landed"
    },
    {
      "flight_id": "BD7E2949",
      "airline": "Delta Air Lines",
      "flight_number": "DL919",
      "departure_city": "Sydney",
      "arrival_city": "Toronto",
      "departure_airport": "Sydney Kingsford Smith Airport",
      "arrival_airport": "Toronto Pearson International Airport",
      "departure_airport_code": "SYD",
      "arrival_airport_code": "YYZ",
      "departure_time": "2025-11-28T13:15:00+10:00",
      "arrival_time": "2025-11-28T02:30:00-05:00",
      "duration": "4h 15m",
      "aircraft_type": "Boeing 737-800",
      "baggage_allowance": "20kg + 7kg",
      "available_classes": ["Economy"],
      "price_usd": 1798.84,
      "seats_available": 26,
      "wifi_available": False,
      "inflight_entertainment": True,
      "status": "Cancelled"
    },
    {
      "flight_id": "20762538",
      "airline": "Qatar Airways",
      "flight_number": "QR979",
      "departure_city": "Toronto",
      "arrival_city": "Singapore",
      "departure_airport": "Toronto Pearson International Airport",
      "arrival_airport": "Singapore Changi Airport",
      "departure_airport_code": "YYZ",
      "arrival_airport_code": "SIN",
      "departure_time": "2025-11-26T22:00:00-05:00",
      "arrival_time": "2025-11-27T18:00:00+08:00",
      "duration": "7h 0m",
      "aircraft_type": "Airbus A380-800",
      "baggage_allowance": "25kg + 7kg",
      "available_classes": ["Economy", "Business", "First"],
      "price_usd": 1077.86,
      "seats_available": 12,
      "wifi_available": True,
      "inflight_entertainment": True,
      "status": "On Time"
    },
    {
      "flight_id": "81041DE5",
      "airline": "Cathay Pacific",
      "flight_number": "CX891",
      "departure_city": "Hong Kong",
      "arrival_city": "Dubai",
      "departure_airport": "Hong Kong International Airport",
      "arrival_airport": "Dubai International Airport",
      "departure_airport_code": "HKG",
      "arrival_airport_code": "DXB",
      "departure_time": "2025-11-07T12:30:00+08:00",
      "arrival_time": "2025-11-07T13:30:00+04:00",
      "duration": "5h 0m",
      "aircraft_type": "Airbus A320",
      "baggage_allowance": "25kg + 7kg",
      "available_classes": ["Economy", "Business", "First"],
      "price_usd": 671.74,
      "seats_available": 32,
      "wifi_available": True,
      "inflight_entertainment": False,
      "status": "Delayed"
    },
    {
      "flight_id": "781AE951",
      "airline": "Singapore Airlines",
      "flight_number": "SQ453",
      "departure_city": "Hong Kong",
      "arrival_city": "Tokyo",
      "departure_airport": "Hong Kong International Airport",
      "arrival_airport": "Narita International Airport",
      "departure_airport_code": "HKG",
      "arrival_airport_code": "NRT",
      "departure_time": "2025-11-09T01:00:00+08:00",
      "arrival_time": "2025-11-09T12:45:00+09:00",
      "duration": "10h 45m",
      "aircraft_type": "Boeing 737 MAX 8",
      "baggage_allowance": "15kg + 7kg",
      "available_classes": ["Economy", "Business", "First"],
      "price_usd": 1624.52,
      "seats_available": 20,
      "wifi_available": True,
      "inflight_entertainment": False,
      "status": "On Time"
    },
    {
      "flight_id": "E5DD7046",
      "airline": "Qantas",
      "flight_number": "QF171",
      "departure_city": "Istanbul",
      "arrival_city": "Paris",
      "departure_airport": "Istanbul Airport",
      "arrival_airport": "Charles de Gaulle Airport",
      "departure_airport_code": "IST",
      "arrival_airport_code": "CDG",
      "departure_time": "2025-11-14T00:15:00+03:00",
      "arrival_time": "2025-11-14T05:00:00+01:00",
      "duration": "6h 45m",
      "aircraft_type": "Airbus A380-800",
      "baggage_allowance": "15kg + 7kg",
      "available_classes": ["Economy", "Business"],
      "price_usd": 2091.61,
      "seats_available": 21,
      "wifi_available": False,
      "inflight_entertainment": False,
      "status": "Cancelled"
    },
    {
      "flight_id": "73FAFD15",
      "airline": "Air France",
      "flight_number": "AF780",
      "departure_city": "Doha",
      "arrival_city": "Singapore",
      "departure_airport": "Hamad International Airport",
      "arrival_airport": "Singapore Changi Airport",
      "departure_airport_code": "DOH",
      "arrival_airport_code": "SIN",
      "departure_time": "2025-11-23T09:15:00+03:00",
      "arrival_time": "2025-11-23T19:00:00+08:00",
      "duration": "4h 45m",
      "aircraft_type": "Boeing 787-9",
      "baggage_allowance": "30kg + 7kg",
      "available_classes": ["Economy", "Business"],
      "price_usd": 2073.57,
      "seats_available": 11,
      "wifi_available": True,
      "inflight_entertainment": False,
      "status": "Cancelled"
    },
    {
      "flight_id": "CC9D5938",
      "airline": "Etihad Airways",
      "flight_number": "EY552",
      "departure_city": "London",
      "arrival_city": "Tokyo",
      "departure_airport": "Heathrow Airport",
      "arrival_airport": "Narita International Airport",
      "departure_airport_code": "LHR",
      "arrival_airport_code": "NRT",
      "departure_time": "2025-11-14T18:30:00+00:00",
      "arrival_time": "2025-11-15T12:15:00+09:00",
      "duration": "8h 45m",
      "aircraft_type": "Airbus A320neo",
      "baggage_allowance": "20kg + 7kg",
      "available_classes": ["Economy", "Business", "First"],
      "price_usd": 1512.33,
      "seats_available": 32,
      "wifi_available": False,
      "inflight_entertainment": False,
      "status": "On Time"
    }
  ]
}

# Minimal dataset (exactly two rows) if you want to toggle for quick demos/tests
# Choose which dataset is active for tools
ACTIVE_DATASET = data  # change to data_two_rows if you want only two rows
